apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: metrics-demo

configMapGenerator:
  - name: server
    files:
      - config/application.properties

resources:
  - backend-service.yaml
  - backend-deployment.yaml
